#include "GarageDoorOpener.h"




void GarageDoorOpener::Main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107--114--6ade1216:15319604bf7:-8000:0000000000000993 begin
{
}
// section -127-21--107--114--6ade1216:15319604bf7:-8000:0000000000000993 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
