#include "InputScanner.h"

// Input scanner thread
// to be run at 1Hz
void* InputThread(void* arg)
{
	char userChoice = 'x';
	// Start the scanning
	do{
		std::cout << "\nEnter your choice: [ ";
		std::cout << "'m' : to indicate motor overcurrent | "
				  << "'i' : to indicate infrared beam interruption | "
				  << "'r' : to indicate remote button press ] : ";

		std::cin >> userChoice;

		switch(tolower(userChoice))
		{
			case 'm': // motor overcurrent
				((InputScanner*)arg)->alertOvercurrent(); // set the shared variable
				break;

			case 'i': // infrared beam interruption
				((InputScanner*)arg)->alertbeam(); // set the shared variable
				break;

			case 'r': // remote button press
				nanospin_ns(1E9); // simulate a 1 second press
				((InputScanner*)arg)->alertbutton(); // set the shared variable
				break;

			default:
				std::cout << "\nInvalid option. Try again" << std::endl << std::endl;
		}

	} while(tolower(userChoice) != 'x');

	return 0;
}


void InputScanner::alertOvercurrent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009D7 begin
{

}
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009D7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void InputScanner::alertbeam()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107-63-c10bd0a:1533defbf13:-8000:0000000000000AD5 begin
{
}
// section -127-21--107-63-c10bd0a:1533defbf13:-8000:0000000000000AD5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void InputScanner::alertbutton()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107-63-c10bd0a:1533defbf13:-8000:0000000000000AD7 begin
{
}
// section -127-21--107-63-c10bd0a:1533defbf13:-8000:0000000000000AD7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


