#include "InputScanner.h"




void InputScanner::alertOvercurrent(void  reciever)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009D7 begin
{
}
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009D7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void InputScanner::alertbeam(void  reciever)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107-63-c10bd0a:1533defbf13:-8000:0000000000000AD5 begin
{
}
// section -127-21--107-63-c10bd0a:1533defbf13:-8000:0000000000000AD5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void InputScanner::alertbutton(void  reciever)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107-63-c10bd0a:1533defbf13:-8000:0000000000000AD7 begin
{
}
// section -127-21--107-63-c10bd0a:1533defbf13:-8000:0000000000000AD7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
