#include "StateContext.h"




void StateContext::transition()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009A4 begin
{
}
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009A4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void StateContext::getActiveState()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009A9 begin
{
}
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009A9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
