#include "State.h"




void State::Entry()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009B1 begin
{
}
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void State::Exit()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009B3 begin
{
}
// section -127-21--107--114--6ade1216:15319604bf7:-8000:00000000000009B3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
